version: 2

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/fsdiff/main.go
    binary: fsdiff
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

changelog:
  disable: true

checksum:
  name_template: "checksums.txt"

archives:
  - name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
