// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: pkg/pb/diff.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Update_Action int32

const (
	Update_ADD    Update_Action = 0
	Update_REMOVE Update_Action = 1
	Update_CHANGE Update_Action = 2
)

// Enum value maps for Update_Action.
var (
	Update_Action_name = map[int32]string{
		0: "ADD",
		1: "REMOVE",
		2: "CHANGE",
	}
	Update_Action_value = map[string]int32{
		"ADD":    0,
		"REMOVE": 1,
		"CHANGE": 2,
	}
)

func (x Update_Action) Enum() *Update_Action {
	p := new(Update_Action)
	*p = x
	return p
}

func (x Update_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Update_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_diff_proto_enumTypes[0].Descriptor()
}

func (Update_Action) Type() protoreflect.EnumType {
	return &file_pkg_pb_diff_proto_enumTypes[0]
}

func (x Update_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Update_Action.Descriptor instead.
func (Update_Action) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_diff_proto_rawDescGZIP(), []int{0, 0}
}

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string        `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Action Update_Action `protobuf:"varint,2,opt,name=action,proto3,enum=pb.Update_Action" json:"action,omitempty"`
}

func (x *Update) Reset() {
	*x = Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_diff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_diff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_pkg_pb_diff_proto_rawDescGZIP(), []int{0}
}

func (x *Update) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Update) GetAction() Update_Action {
	if x != nil {
		return x.Action
	}
	return Update_ADD
}

type Diff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedAt int64     `protobuf:"varint,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Updates   []*Update `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *Diff) Reset() {
	*x = Diff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_diff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diff) ProtoMessage() {}

func (x *Diff) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_diff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diff.ProtoReflect.Descriptor instead.
func (*Diff) Descriptor() ([]byte, []int) {
	return file_pkg_pb_diff_proto_rawDescGZIP(), []int{1}
}

func (x *Diff) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Diff) GetUpdates() []*Update {
	if x != nil {
		return x.Updates
	}
	return nil
}

var File_pkg_pb_diff_proto protoreflect.FileDescriptor

var file_pkg_pb_diff_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x69, 0x66, 0x66, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x72, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x29, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x29, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x44,
	0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x02, 0x22, 0x4b, 0x0a, 0x04, 0x44,
	0x69, 0x66, 0x66, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x24, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x67, 0x65, 0x6c, 0x69, 0x6e, 0x69, 0x2f,
	0x66, 0x73, 0x64, 0x69, 0x66, 0x66, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_diff_proto_rawDescOnce sync.Once
	file_pkg_pb_diff_proto_rawDescData = file_pkg_pb_diff_proto_rawDesc
)

func file_pkg_pb_diff_proto_rawDescGZIP() []byte {
	file_pkg_pb_diff_proto_rawDescOnce.Do(func() {
		file_pkg_pb_diff_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_diff_proto_rawDescData)
	})
	return file_pkg_pb_diff_proto_rawDescData
}

var file_pkg_pb_diff_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_pb_diff_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_pb_diff_proto_goTypes = []interface{}{
	(Update_Action)(0), // 0: pb.Update.Action
	(*Update)(nil),     // 1: pb.Update
	(*Diff)(nil),       // 2: pb.Diff
}
var file_pkg_pb_diff_proto_depIdxs = []int32{
	0, // 0: pb.Update.action:type_name -> pb.Update.Action
	1, // 1: pb.Diff.updates:type_name -> pb.Update
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_pb_diff_proto_init() }
func file_pkg_pb_diff_proto_init() {
	if File_pkg_pb_diff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_diff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_diff_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_diff_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_pb_diff_proto_goTypes,
		DependencyIndexes: file_pkg_pb_diff_proto_depIdxs,
		EnumInfos:         file_pkg_pb_diff_proto_enumTypes,
		MessageInfos:      file_pkg_pb_diff_proto_msgTypes,
	}.Build()
	File_pkg_pb_diff_proto = out.File
	file_pkg_pb_diff_proto_rawDesc = nil
	file_pkg_pb_diff_proto_goTypes = nil
	file_pkg_pb_diff_proto_depIdxs = nil
}
