name: Main benchmark

on:
  push:
    branches:
      - main

permissions:
  deployments: write
  contents: write

jobs:
  benchmark:
    name: Performance benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
      - name: Install fixture node apps
        run: |
          cd fixtures/example-react-app && yarn
          cd fixtures/example-react-app-libraries && yarn
      - name: Run benchmark
        run: make bench | tee output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark-v1
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "fsdiff Benchmark"
          tool: 'go'
          output-file-path: output.txt
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true