name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: experimental-features = nix-command flakes
      - run: nix flake check

      - uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true
      - name: goreleaser release --rm-dist
        run: nix develop -c goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
