name: Test

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: experimental-features = nix-command flakes
      - run: nix flake check
      - name: Build
        run: nix develop -c make build
      - name: Test
        run: nix develop -c make test

  benchmark:
    name: Performance benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: experimental-features = nix-command flakes
      - run: nix flake check
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install fixture node apps
        run: |
          cd $GITHUB_WORKSPACE/test/fixtures/example-react-app && yarn
          cd $GITHUB_WORKSPACE/test/fixtures/example-react-app-libraries && yarn
      - name: Run benchmark
        run: |
          set -o pipefail
          nix develop -c make bench | tee output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark-v1
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "fsdiff Benchmark"
          tool: "go"
          output-file-path: output.txt
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
